### ISSUE TITLE
sankeymatic.com/build svg generates broken svg

### ISSUE THREAD

**Issue by gm3dmo** [nowthis/sankeymatic#34] opened 2018-03-06 16:39 UTC
sankeymatic.com/build svg generates broken svg

This page contains the following errors:
error on line 1 at column 534: Entity 'rarr' not defined
Below is a rendering of the page up to the first error.

To reproduce, go to sankeymatic.com/build.
Recover the SVG and save as demo.svg
Browse to file:///demo.svg
The error message above appears.

Workaround
use ```s/&rarr//g``` on the file to make the svg visible again.

**Comment by nowthis** [comment] 2018-03-06 17:27
Correct. Thanks for the report.

This was a regression introduced when I was trying to eliminate a special non-ASCII character from the SVG output. Turns out some SVG parsers don't handle HTML entities without them being specifically called out as such in the markup.

I will fix this as soon as I can; in the meantime a workaround which preserves the right-arrow character in the tooltips is to replace all instances of `&rarr;` with `&#8594;` (or if the tooltip's arrow is not important, your workaround serves the same purpose).

**Comment by nowthis** [comment] 2018-03-07 19:39
@gm3dmo -

The live site should be producing usable SVG again: http://sankeymatic.com/build/

Please let me know if it's failing for you in any way now.

I'll get the changes checked in and pushed to GitHub in the next couple of days as well.

**Closed** 2018-07-26 13:19 UTC
